name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/MOODLE_39_STABLE'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd ${{ secrets.PROJECT_PATH }} && sudo -u moodle /usr/bin/php admin/cli/maintenance.php --enable && git pull && sudo -u moodle /usr/bin/php admin/cli/upgrade.php && sudo -u moodle /usr/bin/php admin/cli/maintenance.php --disable
